paths:
  directory: "/cosma8/data/dp004/flamingo/Runs/"
  simulation: "L2800N5040/HYDRO_FIDUCIAL"
  soap_hbt_subpath: "SOAP-HBT/halo_properties_00"
  redshift_file: "output_list.txt"
  snapshot_number: 72 #for numbers below 10, fill in 06 or 07, not 6 and 7

slicing:
  method: "single" #or "multiple"
  n_slices: 20
  

distance: # in Mpc
  min: 100
  max: 220
  type: angular #or euclidean

random_catalog:
  seed: 12345
  oversampling: 2 #the oversampling factor of the randoms

filters:
  central_filter: off
  stellar_mass_filter: on
  stellar_mass_cutoff: 70 #percentile that is excluded
  luminosity_filter: on
  band: r  #observed band
  m_cutoff: 19  #apparent magnitude of the band of the observer
  

plotting:
  bins: 200
  leafsize: 100

statistics:
  variance_method: jackknife #or bootstrap
  n_patches: 100
