paths:
  directory: /cosma8/data/dp004/flamingo/Runs/ #do not touch!
  soap_hbt_subpath: SOAP-HBT/halo_properties_00 #do not touch!

  simulation: L2800N5040/HYDRO_FIDUCIAL #only thouch this part!
  redshift_file: output_list.txt
  #we might wanna get the snapshotnumber outside of the config.yaml file to automate further!
  snapshot_number: [60,61,62,63,64,65,66] #for numbers below 10: fill in 06 or 07, not 6 and 7
  output_directory: results_angular_2 #full path if necessary

slicing:
  method: single #single or multiple
  n_slices: 20  #if you choose for multiple, this measures cosmic variance
  bin_width: 0.2 #delta_z of the complete bin, will mark the shell volume
  

distance: # in Mpc
  min: 50
  max: 250
  type: angular # angular or euclidean

random_catalog:
  seed: 12345 #random number, not very interesting to look at , We could later add None to recreate uncontrolled randoms.
  oversampling: 20 #the oversampling factor of the randoms

filters:
  central_filter: off
  stellar_mass_filter: on
  stellar_mass_cutoff: 0
  luminosity_filter: on
  band: r  #observed band
  m_cutoff: 24 #apparent band magnitude for the observer
  

plotting:
  bins: 40
  leafsize: 100  #might be deleted later on, only useful in old_correlation.py

statistics:
  variance_method: jackknife #bootstrap,jackknife,simple(n_patches=1)
  n_patches: 40
